[SP-63] added Backend query for Login
MediocreMarcel/SP pull request #16
Opened 2020-11-23 17:42 UTC by arthi1997

- added Backend query for Login
- added Errorhandling
- added Codedocumentation

2020-11-24 18:21 UTC, MediocreMarcel requested changes
Siehe Anmerkungen

2020-11-24 18:21 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/db_access/DBUser.java
> +            return resultSetMapper.mapResultSetToObject(rs, UserDao.class).get(0);
Was passiert, wenn die List leer ist? Ein direkter get ohne check sollte vermieden werden

2020-11-24 18:21 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/handler/UserHandler.java
> +    public Response loginUser(UserDao user) throws SQLException {
Methode sollte keine SQLException werfen. Abfangen mit Try/Catch und fehler beheben oder ausgeben

2020-11-24 18:21 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/dao/UserDao.java
> +
Java-Doc mit einem satz für was das dto nötig ist wäre gut aber nicht nötig

2020-11-25 10:37 UTC, arthi1997 commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/db_access/DBUser.java
> +            return resultSetMapper.mapResultSetToObject(rs, UserDao.class).get(0);
(/)

2020-11-25 10:39 UTC, arthi1997 commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/handler/UserHandler.java
> +    public Response loginUser(UserDao user) throws SQLException {
done

2020-11-25 10:57 UTC, MediocreMarcel approved these changes
LGTM

2020-11-25 10:57 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/dao/UserDao.java
> +public class UserDao {
Bitte zu UserDto Umbenennen. Genauso wie den Ordner

2020-11-25 10:57 UTC, merged