createExamenReset
MediocreMarcel/SP pull request #18
Opened 2020-11-30 09:05 UTC by PTsiali

Fragen backend

2020-12-01 14:11 UTC, Nevermint commented on Frontend/SPFrontend/src/app/app.module.ts
> -    HomePageComponent,
Warum wurde HomePageComponent entfernt?

2020-12-01 14:12 UTC, Nevermint commented on Frontend/SPFrontend/src/app/app.component.html
> +<app-create-exam></app-create-exam>
Der Verweis zum NAvigieren muss ins routing.modules.ts

2020-12-02 11:08 UTC, Nevermint reviewed
Rename Pojo to DTO & Rebase with main

2020-12-04 22:24 UTC, MediocreMarcel requested changes

2020-12-04 22:24 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/handler/QuestionsHandler.java
> +    @Path("newQuestion")
Please add javadoc

2020-12-04 22:24 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/handler/QuestionsHandler.java
> +
please add javadoc

2020-12-04 22:26 UTC, MediocreMarcel requested changes

2020-12-04 22:26 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/Pojo/QuestionsPojo.java
> +public class QuestionsPojo {
Rename to DTO also move to dto folder

2020-12-04 22:26 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/dao/ModuleDao.java
> +public class ModuleDao {
Change to DTO, also change folder

2020-12-04 22:26 UTC, MediocreMarcel commented on Backend/src/main/java/de/hft_stuttgart/winf/proj2/sp/backend/dao/UserDao.java
> +public class UserDao {
Change to dto and move to folder

2021-01-08 09:42 UTC, closed without merging